
namespace KingOfDiamonds
{
    class Welcome
    {
        public void Print()
        {
            Console.WriteLine("Welcome to the KING OF DIAMONDS!!");
            Console.WriteLine("You will have another 4 players playing with you.");
            Console.WriteLine("Each player will enter any number from 0 to 10.");
            Console.WriteLine("The average of all of your guesses will be multiplied by 0.8.");
            Console.WriteLine("Whoever gets the closet guess will win the round.");
            Console.WriteLine("The winner will get 1 point and the other will lost 2 each.");
            Console.WriteLine("Whoever reaches -10 will be eliminated from the game.");
            Console.WriteLine("Each player will have 0 point to start");
            Console.WriteLine("Let the game begin!!");
        }
    }
}